### ISSUE TITLE
Feat: the difference with EVM when Exocore Gateway communicats with Solana

### ISSUE THREAD

**Issue by magj2006** [ExocoreNetwork/exocore-contracts#119]
Here are some of the differences observed so far when Exocore gateway communicates with Solana and the EVM:

1. EVM uses OrderedOptions, Solana uses UnorderedOptions 
2. In the call to addTokenWhiteList, when using addExecutorLzReceiveOption to construct Options, set a non-zero value
3. needs token program param when calling addTokenWhiteList, in case of create token account for pool .
4. needs token and user to get vault PDA account when receiving respond message. 

<img width="922" alt="截屏2024-10-27 00 10 25" src="https://github.com/user-attachments/assets/aac4a5a5-4254-4f2f-9188-178fe1b6586d">

The red box marks the ones that need to be added

**Comment by adu-web3** [comment]
for all these problems, we can specialize the function of ExocoreGateway to add custom options or extra params when sending messages to solana. Especially for problem 1, we can use unordered option first and wait for future support for ordered option

for problem 3, does this approach(https://github.com/ExocoreNetwork/exocore-contracts/issues/98#issuecomment-2381091231) works for it? this might help with reducing the messaging fee by lessening the message

**Comment by magj2006** [comment]
for 3: there are two way to update, first is adding one more param, like as : function addWhitelistToken(
        uint32 clientChainId,
        bytes32 token,
        uint8 decimals,
        string calldata name,
        string calldata metaData,
        string calldata oracleInfo,
        uint128 tvlLimit,
        bytes1 tag
    ) , another is adding new function which is only called for solana, like as: function addWhitelistTokenSolana(
        uint32 clientChainId,
        bytes32 token,
        uint8 decimals,
        string calldata name,
        string calldata metaData,
        string calldata oracleInfo,
        uint128 tvlLimit,
        bytes1 tag
    ) , which one is better ? 

<img width="860" alt="截屏2024-10-28 10 19 52" src="https://github.com/user-attachments/assets/7e26a17a-6fd6-4045-8002-d646b06d09a1">

**Comment by adu-web3** [comment]
adding a tag should be more straightforward. But in this case, you might still need to check whether the token program passed from exocore is correct, since the contract caller might fill in the false tag

**Comment by magj2006** [comment]
> adding a tag to existing function should be more straightforward. But in this case, you might still need to check whether the token program passed from exocore is correct, since the contract caller might fill in the false tag

Yes, you are right. the caller should check the owner of token, then pass the correct tag.
