### ISSUE TITLE
[feature] add different logic to process DepositNST from Solana client

### ISSUE THREAD

**Issue by magj2006** [ExocoreNetwork/exocore-contracts#135]
On the Solana chain, after the user has done native stake, if he wants to do restaking on ExoCore, it will be a little different from EVM. The EVM client verifies the validator information through proof, and then passes  validatorIndex in proof to the ExoCore contract  Solana handles it differently here. For each user who has done native stake, it will generate a stake_account. The staking information from user will be stored in this stake_account, which is created by stake program. so when sending the DepositNST message, the message content here will be different from that of EVM. The message it sends likes: abi.encode(stake_account, user, amount).

![image](https://github.com/user-attachments/assets/27291e96-2815-4ee7-9a6e-e56e96ee4f28)

**Comment by adu-web3** [comment]
the current message format for `REQUEST_DEPOSIT_NST` action is:
https://github.com/ExocoreNetwork/exocore-contracts/blob/321a7e2637f9eeb5aa78fd30adcd410f84221b99/src/core/NativeRestakingController.sol#L97

what's the difference?
