### ISSUE TITLE
[security] Claim only to `msg.sender`

### ISSUE THREAD

**Issue by MaxMustermann2** [ExocoreNetwork/exocore-contracts#27]
Currently, our claim function is as follows.

```solidity
function claim(address token, uint256 amount, address recipient)
```

However, it should be changed to this.

```solidity
function claim(address token, uint256 amount)
```

This is to reduce the attack vector, and align with the advice that Exocore acts a trust-minimized L1 and that the withdrawal address equals the deposit address for all stakers.

**Comment by adu-web3** [comment]
the `recipient` is later added as a feature: staker could specify a destination address(an EOA address or a contract address) as recipient address. If we remove this argument, we would disable this feature. So it depends on whether we need this feature
