### ISSUE TITLE
[LST][Optimization] save LayerZero relaying fee by not sending response back for deposit/delegate/undelegate

### ISSUE THREAD

**Issue by adu-web3** [ExocoreNetwork/exocore-contracts#3]
## Description

For delegate/undelegate, the current workflow would send back response from Exocore to `ClientChainGateway` so that we could emit an `DelegateResult`/`UndelegateResult` event to inform client chain about the operation result. Actually this responses do not modify state variables like `principleBalance` or `withdrawableBalance`, and especially undelegate operation is a delayed operation, which means  `DelegateResult` should mean delegate request is received by Exocore and is executed and `UndelegateResult` should mean undelegate request is received by Exocore and would be executed after a delay, so we might not need to return a response to `ClientChainGateway`.

For deposit, things are a little different: we should have returned the response from Exocore in case the deposit had failed for any reason, thus we should unlock or send back the tokens that were previously locked in the vault, but if we assume that deposit must succeed in any case, the response could even be avoided. Even though deposit response would modify `lastlyUpdatedPrinciple` value in vault for staker, this value actually has no influence in current design.

**Comment by adu-web3** [comment]
I have talked with @bwhour about whether we should take deposit failure as protocol exception: If we take deposit failure as protocol exception, once deposit failure happened, the whole protocol is halted as the failed deposit request would block future requests and we can't resume the protocol unless we upgrade `exocored` to replay deposit request to make it pass, otherwise we should add corresponding logic to `ClientGatewayLzReceiver` to unlock or even sends funds to the depositor in case deposit request failed. 

So @TimmyExogenous @MaxMustermann2 , what do you think about this? Do you think we should take deposit failure as ordinary error and add corresponding logics for failed case or we could take it as protocol exception and avoid logics for bad case?

**Comment by MaxMustermann2** [comment]
The `deposit` precompile rejects the deposit if _any_ of the following are true:

- The caller is not the `ExocoreGateway` address in the `x/assets` module parameters
- The parameters for the precompile call are not well formatted or inaccurate (for example, wrong address length)
- The asset is not registered
- The total supply of the asset is less than the deposited supply (including the additional deposit made in this call)

Assuming our deployments are right, points 1 and 2 cannot be true. But point 3 can be true: for example, if there is a lag in registering a token on Exocore chain but the token has been registered on `ClientChainGateway`. Point 4 can be true if there is something wrong in the data provided to the `x/assets` module during token registration, **or** there is something extremely malicious going on.

Among these cases, I think we should guard against the possibility of point 3 being true, while the possibility of malicious activity should be handled by a strong external audit. To that end, in calls to `ClientChainGateway.addWhitelistToken`, we should check via LZ if that token is registered in the `x/assets` module first. What do you think?

**Comment by adu-web3** [comment]
this is a detailed and wonderful investigation into this problem.

As for point 3, I think we could avoid by registering/deregistering asset from client chain to asset module, that is when calling `addWhitelistToken/removeWhitelistToken`, a cross-chain message would be forwarded to Exocore to be handled just like deposit/withdraw, and only add token id to the whitelist of client chain contract after receiving a response that indicates asset module successfully handles the registry/deregistry command, like what is described in this issue: https://github.com/ExocoreNetwork/exocore-contracts/issues/12

This approach also helps alleviate the governance problem of assets registry, by trusting the multi-sig wallet which is the contract owner, though we might finally need to figure out the governance mechanism of it for example by govern proposal of govern module.

To register an asset to whitelist, we should register the client chain first. From contracts perspective, this could be done by calling`ExocoreGateway.setPeer`(maybe we should consider calling `ClientChainGateway.setPeer` in initialization logic?), so  only need to do one more step to make work for asset module: register client chain to asset module when calling ExocoreGateway.setPeer`.

This is the rough solution for point 3, what do you think @MaxMustermann2

**Comment by MaxMustermann2** [comment]
I agree with this approach. Once this approach is implemented, a failure in deposits should be considered a protocol breaking fault.
